agent {
    trust_domain = "aegis-ot.m4g.local"
    data_dir = "/var/lib/spire/agent"
    log_level = "INFO"
    server_address = "spire-server"
    server_port = "8081"
    socket_path = "/run/spire/agent/public/api.sock"
    trust_bundle_path = "/run/spire/bootstrap/bundle.pem"
    join_token_file = "/run/spire/bootstrap/join-token"
}

plugins {
    NodeAttestor "join_token" {
        plugin_data {}
    }

    KeyManager "disk" {
        plugin_data {
            directory = "/var/lib/spire/agent"
        }
    }

    WorkloadAttestor "unix" {
        plugin_data {
            discover_workload_path = false
            workload_size_limit = -1
        }
    }
}
