[management]
management ansible_host=192.168.56.10 aegis_role=management

[trust]
trust ansible_host=192.168.56.11 aegis_role=trust

[agents]
agents ansible_host=192.168.56.12 aegis_role=agents

[gateway]
gateway ansible_host=192.168.56.13 aegis_role=gateway

[ot]
ot ansible_host=192.168.56.14 aegis_role=ot

[simulation]
simulation ansible_host=192.168.56.15 aegis_role=simulation

[all:vars]
ansible_user=vagrant
ansible_python_interpreter=/usr/bin/python3
